# Generated by Django 4.2.11 on 2024-05-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="signin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(default="", max_length=20)),
                ("Age", models.IntegerField(default="")),
                ("Contact", models.IntegerField(default="")),
                ("Address", models.CharField(default="", max_length=50)),
                ("Mail", models.CharField(default="", max_length=50)),
            ],
        ),
    ]
