# Generated by Django 5.0.4 on 2024-05-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_datas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signin',
        ),
    ]
